### PR TITLE
Hard pinning dbt-core to 1.4

### PR DESCRIPTION
**Pull request by callum-mcdata**
This PR addresses issue #475

### CODE REVIEW

**Comment by callum-mcdata** [comment]
@QMalcolm would you have any idea why the below errors would be triggered if I've hard pinned our dev testing to 1.4?

> metricflow/model/transformations/dbt_to_metricflow.py:8: error: Module "dbt.exceptions" has no attribute "ref_invalid_args"  [attr-defined]
metricflow/model/transformations/dbt_to_metricflow.py:113: error: Missing positional argument "target_model_version" in call to "resolve_ref" of "Manifest"  [call-arg]
Found 2 errors in 1 file (checked 355 source files)

I am able to recreate it locally but I am very confused because `target_model_version` would only exist in 1.5.

**Comment by QMalcolm** [comment]
> @QMalcolm would you have any idea why the below errors would be triggered if I've hard pinned our dev testing to 1.4?
> 
> > metricflow/model/transformations/dbt_to_metricflow.py:8: error: Module "dbt.exceptions" has no attribute "ref_invalid_args"  [attr-defined]
> > metricflow/model/transformations/dbt_to_metricflow.py:113: error: Missing positional argument "target_model_version" in call to "resolve_ref" of "Manifest"  [call-arg]
> > Found 2 errors in 1 file (checked 355 source files)
> 
> I am able to recreate it locally but I am very confused because `target_model_version` would only exist in 1.5.

I think agree, `target_model_version` doesn't exist in 1.4. Locally it looks correct with 1.4 installed. I can't see in the failing job what verion of dbt is being installed 🤔 My guess is that the job is still getting 1.5 for whatever reason

**Comment by QMalcolm** [comment]
> > ...
> 
> I think agree, `target_model_version` doesn't exist in 1.4. Locally it looks correct with 1.4 installed. I can't see in the failing job what verion of dbt is being installed 🤔 My guess is that the job is still getting 1.5 for whatever reason

So on [line 15 of Run Linter](https://github.com/dbt-labs/metricflow/actions/runs/4822118216/jobs/8588922358?pr=476#step:6:16) it looks like it gets the types for dbt-core via a mypi-mirror (https://github.com/pre-commit/mirrors-mypy:dbt-core) but it doesn't specify a version. My guess is that gets the latest?

**Comment by QMalcolm** [comment]
@callum-mcdata I think I found the issue. We also need to correctly constrain the dbt-core version referenced in [.pre-commit-config.yaml](https://github.com/dbt-labs/metricflow/blob/8800ed5e36e2f7795d458fd46564aeb9f991a995/.pre-commit-config.yaml#L34)

**Review by QMalcolm — APPROVED** [review]
Looks great to me! 🚀

**Pull request merged**
