### PR TITLE
Tests for simple metrics with sub-daily dimensions

### PR DESCRIPTION
**Pull request by courtneyholcomb**
Per title. Just tests!

### CODE REVIEW

**Comment by plypaul** [comment]
Seems like it's just the last 3 commits, but can you rebase?

**Comment by courtneyholcomb** [comment]
> Seems like it's just the last 3 commits, but can you rebase?

**Comment by courtneyholcomb** [comment]
@plypaul updated, sorry about that!!

**Review by tlento — APPROVED** [review]
This seems reasonable for the secondary time dimension scenarios. I assume the metric_time testing is upstack.

**Comment by courtneyholcomb** [comment]
> This seems reasonable for the secondary time dimension scenarios. I assume the metric_time testing is upstack.

@tlento it's not. I'll add some more at the top of stack querying with `metric_time` and the interaction between sub-daily and default granularity.

**Pull request merged**
