### PR TITLE
Remove unused DimensionSpecResolver class

### PR DESCRIPTION
**Pull request by tlento**
The DimensionSpecResolver did something or other with where
clause inputs, but it is not used anymore, if it ever was.

### CODE REVIEW

**Comment by tlento** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dbt-labs/metricflow/1389?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1390** <a href="https://app.graphite.dev/github/pr/dbt-labs/metricflow/1390?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1389** <a href="https://app.graphite.dev/github/pr/dbt-labs/metricflow/1389?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1387** <a href="https://app.graphite.dev/github/pr/dbt-labs/metricflow/1387?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1386** <a href="https://app.graphite.dev/github/pr/dbt-labs/metricflow/1386?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1385** <a href="https://app.graphite.dev/github/pr/dbt-labs/metricflow/1385?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tlento and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by courtneyholcomb — APPROVED** [review]
just checking - I assume you already checked to make sure this isn't used in other repos? If so thennnn :shipit:

**Comment by tlento** [comment]
> just checking - I assume you already checked to make sure this isn't used in other repos? If so thennnn

I did, checked MFS locally and used GitHub search for the org. Seems ok!

**Comment by tlento** [comment]
### Merge activity

* **Sep 3, 3:08 PM PDT**: @tlento started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dbt-labs/metricflow/1389).

**Pull request merged**
